'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={menu:'M3 5h18M3 12h12M3 19h6',home:'M3 10 12 3l9 7v10H4V10M9 21v-8h6v8',file:'M14 2H5v20h14V7l-5-5v5h5M8 12h8M8 16h6',send:'m3 3 19 8-9 3-3 8-7-19Zm10 11 9-3',folder:'M3 7h7l2 2h9v11H3V5h6l2 2',palette:'M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 0-4c-1-1 0-2 2-2h2a5 5 0 0 0 4-5c0-4-4-7-9-7M7 10h.01M9 6h.01M15 6h.01M18 10h.01',tool:'m14 6 4 4M5 20l-2-2 9-9c-1-4 2-7 6-6l-4 4 3 3 4-4c1 4-2 7-6 6Z',code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',text:'M3 4h18M12 4v16M7 20h10',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',play:'m8 4 13 8-13 8Z',check:'m5 12 4 4L20 5',plus:'M12 4v16M4 12h16',arrow:'M5 12h14m-6-6 6 6-6 6',cut:'m9 9 11 11M9 15 20 4M5 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8M5 14a4 4 0 1 0 0 8 4 4 0 0 0 0-8',copy:'M8 8h13v13H8ZM16 8V3H3v13h5',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',image:'M3 3h18v18H3Zm0 13 5-6 7 8 3-4 3 3M16 7h.01',hash:'M9 3 7 21M17 3l-2 18M3 8h18M2 16h18',archive:'M3 5h18v5H3Zm2 5v11h14V10M10 14h4',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Zm10-3a3 3 0 1 0 0 6 3 3 0 0 0 0-6',link:'m10 13 4-4M8 15l-2 2a3 3 0 0 1-4-4l5-5a3 3 0 0 1 4 0m2 8a3 3 0 0 0 4 0l5-5a3 3 0 0 0-4-4l-2 2',disk:'M4 4h16v16H4Zm8 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8M17 17h.01',qr:'M3 3h6v6H3ZM15 3h6v6h-6ZM3 15h6v6H3ZM15 15h3v3h3v3h-6Zm6-3h.01',close:'m6 6 12 12M6 18 18 6',pin:'m8 3 8 0-1 7 4 4H5l4-4ZM12 14v8',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z'};
function icon(n){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.tool}"/></svg>`}
const nav=[['overview','home','概览'],['templates','file','新建文件'],['send','send','发送文件'],['favorites','folder','常用目录'],['icons','palette','文件夹图标'],['tools','tool','工具箱'],['apps','code','开发工具'],['text','text','文字工具'],['workbench','play','操作台'],['menu','menu','右键菜单'],['settings','settings','通用设置']];
let model,config,page='overview',cwd='',selection=[],lastResult=null,lastLabel='',textValue='',statusInfo={},installedApps=[],serial=0,pending=new Map(),busy=false;
window.__resolve=(id,result)=>{const p=pending.get(id);if(!p)return;pending.delete(id);result.ok?p.resolve(result.data):p.reject(new Error(result.error||'操作失败'))};
function rpc(request){return new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});if(!window.webkit?.messageHandlers?.rustclick){pending.delete(id);reject(new Error('请从 RightClick.app 打开此界面'));return}window.webkit.messageHandlers.rustclick.postMessage({id,request})})}
const native=(cmd,params={})=>rpc({cmd:'native',request:{cmd,...params}});
let toastTimer;function toast(text,error=false){$('#toast').textContent=text;$('#toast').className='toast visible'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),error?6500:3500)}window.showError=e=>toast(e,true);window.addEventListener('unhandledrejection',e=>{e.preventDefault();toast(e.reason?.message||String(e.reason),true)});
async function reload(){model=await rpc({cmd:'state'});config=model.config;model.menuCatalog=await native('menu_catalog',{config});cwd=cwd||model.home+'/Desktop';$('#choose-context').textContent=cwd;return model}
async function save(){await rpc({cmd:'save_config',config});await native('apply_settings',{config});model.menuCatalog=await native('menu_catalog',{config});toast('设置已保存');render()}
function switchButton(key,value,label){return `<button class="switch ${value?'on':''}" data-setting="${key}" role="switch" aria-checked="${!!value}" aria-label="${esc(label)}"></button>`}
function title(eyebrow,name,sub,action=''){return `<div class="eyebrow">${eyebrow}</div><div class="title-line"><h1>${name}</h1>${action}</div><p class="subtitle">${sub}</p>`}
function context(){return `<div class="file-context"><div class="tile-icon">${icon('folder')}</div><div class="text"><h3>${selection.length?`已选择 ${selection.length} 个项目`:'选择文件，开始操作'}</h3><small>${esc(cwd)}</small></div><button class="secondary" data-action="choose-dir">更改目录</button><button class="primary" data-action="choose-files">${icon('plus')}选择文件</button></div>${selection.length?`<div class="selected-files">${selection.map(p=>`<span class="file-chip" title="${esc(p)}">${esc(p.split('/').pop())}</span>`).join('')}<button class="inline-link" data-action="clear-files">清除</button></div>`:''}`}
const cards=[['templates','file','新建文件','从一份空白，或你熟悉的模板开始。','blue'],['send','send','复制与移动','送到常用目录，少打开几个窗口。','green'],['apps','code','在此处打开','让终端与编辑器，直达当前目录。','purple'],['icons','palette','文件夹图标','用颜色和图标，标记自己的秩序。','orange'],['tools','tool','文件工具箱','格式转换、压缩、校验，都在这里。','gray'],['text','qr','文字与二维码','随手生成二维码，快速翻译文字。','green']];
function overview(){return `<section class="launch-hero"><div class="launch-copy"><div class="eyebrow">RIGHTCLICK FOR MAC</div><h1>每一次右键。<br><span>都更进一步。</span></h1><p>文件、灵感、工作流。<br>你需要的工具，近在手边。</p><div class="hero-actions"><button class="primary" data-page="menu">定制你的右键</button><button class="hero-link" data-page="workbench">打开操作台 ${icon('arrow')}</button></div></div><div class="product-stage" aria-hidden="true"><div class="stage-halo"></div><div class="stage-folder"><span></span></div><div class="stage-document"><span>Aa</span><i></i><i></i><i></i></div><div class="stage-menu"><div class="stage-menu-caption">你的下一步，就在这里。</div><div class="stage-menu-row selected">${icon('plus')}<span>新建文件</span><b>›</b></div><div class="stage-menu-row">${icon('copy')}<span>复制到…</span><b>›</b></div><div class="stage-menu-row">${icon('code')}<span>在终端中打开</span></div><div class="stage-menu-divider"></div><div class="stage-menu-row">${icon('link')}<span>拷贝路径</span></div><div class="stage-menu-row">${icon('image')}<span>转换图片</span><b>›</b></div><div class="stage-menu-row">${icon('hash')}<span>文件信息</span></div></div><div class="stage-cursor"><svg viewBox="0 0 48 56"><path d="M6 4v39l11-11 9 19 8-4-9-18h16Z" fill="white" stroke="#202126" stroke-width="2.5" stroke-linejoin="round"/></svg></div></div><div class="launch-caption"><span>为 Mac 而设计</span><i></i><span>所有功能，永久开放</span></div></section><div class="section-label feature-heading"><h2>小操作。<span>大有可为。</span></h2><span>让专注，留给更重要的事。</span></div><div class="grid">${cards.map(([id,i,t,d,c])=>`<button class="feature-card" data-page="${id}"><div class="tile-icon ${c}">${icon(i)}</div><span class="arrow">↗</span><h3>${t}</h3><p>${d}</p></button>`).join('')}</div><div class="setup"><div class="step-dot">${statusInfo.finderEnabled?'✓':'1'}</div><div class="text"><h3>${statusInfo.finderEnabled?'一切就绪，右键即用。':'从访达，开始你的新体验。'}</h3><p>${statusInfo.finderEnabled?'访达扩展已启用。你的工具，已在熟悉的位置。':'启用访达扩展，即可使用右键菜单和窗口工具栏。'}</p></div><button class="secondary" data-action="enable-finder">${statusInfo.finderEnabled?'查看设置':'前往启用'} ${icon('arrow')}</button></div>`}

function templatesPage(){const rows=[...model.formats,...config.templates.map(t=>({...t,custom:true,color:'purple',enabled:t.enabled!==false}))];return title('START WITH A FILE','新建文件','让一个常用文件，诞生在你需要它的地方。',`<div class="row-actions"><button class="secondary" data-tool="create_custom">自定义新建</button><button class="primary" data-action="add-template">${icon('plus')}导入模板</button></div>`)+`<div class="panel"><div class="panel-title"><h3>文件类型与模板</h3><span class="muted">${rows.length} 种格式</span></div>${rows.map(f=>`<div class="row"><div class="tile-icon ${f.color}">${icon('file')}</div><div class="text"><strong>${esc(f.name)}</strong><small>${f.custom?'你的自定义模板':'内置文件模板'}</small></div><span class="ext">.${esc(f.ext)}</span><div class="row-actions"><button class="secondary" data-create="${esc(f.id)}" data-custom="${!!f.custom}">新建</button>${f.custom?`<button class="icon-button" data-remove-template="${esc(f.id)}" aria-label="移除模板">${icon('close')}</button>`:switchButton('format:'+f.id,!config.disabled.includes('format:'+f.id),f.name+'右键菜单')}</div></div>`).join('')}</div><div class="note">Pages、Numbers、Keynote、WPS 或任何专用格式：导入你自己保存的空白文档或模板，即可原样创建；模板会独立保存。AI 内置模板采用可编辑的 EPS 兼容格式。</div>`}
function foldersPage(kind){return title('EVERYTHING IN ITS PLACE',kind==='send'?'发送文件':'常用目录',kind==='send'?'不用层层打开文件夹，把文件送到正确的位置。':'那些经常到达的地方，始终近在手边。',`<button class="primary" data-action="add-favorite">${icon('plus')}添加目录</button>`)+(kind==='send'?context():'')+`<div class="panel">${config.favorites.map((f,i)=>`<div class="row"><div class="tile-icon blue">${icon('folder')}</div><div class="text"><strong>${esc(f.name)}</strong><small>${esc(f.path)}</small></div><div class="row-actions">${kind==='send'?`<button class="secondary" data-transfer="copy" data-index="${i}">复制到</button><button class="secondary" data-transfer="move" data-index="${i}">移动到</button>`:`<button class="secondary" data-open-favorite="${i}">打开</button>`}<button class="icon-button" data-edit-favorite="${i}" aria-label="重命名目录显示名称">${icon('text')}</button><button class="icon-button" data-remove-favorite="${i}" aria-label="从常用目录移除">${icon('close')}</button></div></div>`).join('')||'<div class="empty">添加第一个常用目录</div>'}</div>${resultView()}`}
const toolsList=[['cut','cut','剪切文件'],['paste','copy','粘贴文件'],['cancel_cut','close','取消剪切'],['copy_path','link','拷贝完整路径'],['copy_name','text','拷贝文件名称'],['info','hash','MD5 / SHA 校验'],['shortcut','link','快捷方式到桌面'],['folder_from_name','folder','按文件名建文件夹'],['dissolve','folder','解散文件夹'],['rename','text','重命名文件'],['repair_name','text','修复乱码文件名'],['hidden','eye','隐藏选中文件'],['unhidden','eye','取消隐藏文件'],['finder_show','eye','显示所有隐藏文件'],['finder_hide','eye','隐藏所有隐藏文件'],['extension_hide','file','隐藏文件扩展名'],['extension_show','file','显示文件扩展名'],['writable','check','授予本人写入权限'],['airdrop','send','隔空投送'],['wallpaper','image','设为桌面墙纸'],['preview','image','预览与标注图片'],['pin','pin','图片置顶贴图'],['screenshot','image','交互式截图'],['scan','disk','扫描目录空间'],['trash','trash','移到废纸篓'],['delete','trash','永久删除']];
const imageTools=[['png','PNG'],['jpg','JPG'],['webp','WebP'],['heic','HEIC'],['icns','ICNS'],['mac_icons','Mac 图标集'],['ios_icons','iOS 图标集']];
function toolButton(id,i,label){return `<button class="tool" data-tool="${id}"><div class="tile-icon">${icon(i)}</div><span>${label}</span></button>`}
function toolsPage(){return title('A LITTLE MORE CAPABLE','工具箱','小而实用。让文件处理，留在当前工作流里。')+context()+`<div class="section-label"><h3>文件与系统</h3><span>本地处理</span></div><div class="tool-grid">${toolsList.map(t=>toolButton(...t)).join('')}</div><div class="section-label"><h3>图片格式转换</h3><span>生成新文件，保留原图</span></div><div class="tool-grid">${imageTools.map(([id,label])=>toolButton('convert:'+id,'image','转为 '+label)).join('')}</div><div class="section-label"><h3>压缩与解压</h3></div><div class="tool-grid">${toolButton('compress','archive','压缩为 ZIP')}${toolButton('compress7z','archive','压缩为 7z')}${toolButton('encrypt','archive','加密压缩')}${toolButton('extract','archive','解压到独立文件夹')}</div>${resultView()}`}
function iconPage(){const colors=[['薰衣草','A087DF'],['雾蓝','7298D5'],['薄荷','78B697'],['杏橙','D9A16E'],['珊瑚','D9868C'],['石墨','8992A0']];return title('COLOR YOUR WORKSPACE','文件夹图标','让每个目录，都有一点自己的个性。')+context()+`<div class="section-label"><h3>选择一种颜色</h3><span>应用于所选文件或文件夹</span></div><div class="color-grid">${colors.map(([n,c])=>`<button class="color-button" style="color:#${c}" data-color="${c}">${icon('folder')}<span>${n}</span></button>`).join('')}</div><div class="panel"><div class="row"><div class="tile-icon purple">${icon('image')}</div><div class="text"><strong>使用自己的图片</strong><small>支持 PNG、JPG、ICNS 等系统支持的图片</small></div><button class="secondary" data-action="custom-icon">选择图片</button></div><div class="row"><div class="tile-icon gray">${icon('folder')}</div><div class="text"><strong>恢复默认图标</strong><small>清除所选项目的自定义图标</small></div><button class="secondary" data-tool="reset_icon">恢复默认</button></div></div>`}
function appsPage(){return title('OPEN WHERE YOU ARE','开发工具','终端、编辑器、IDE，在当前目录接着工作。',`<button class="primary" data-action="add-app">${icon('plus')}添加应用</button>`)+context()+`<div class="panel">${config.apps.map((a,i)=>`<div class="row"><div class="tile-icon ${i<2?'gray':'purple'}">${icon('code')}</div><div class="text"><strong>${esc(a.name)}</strong><small>${installedApps.find(x=>x.id===a.id)?.installed?'已安装 · '+esc(a.id):'选择已安装的应用可添加任意编辑器'}</small></div><div class="row-actions"><button class="secondary" data-open-app="${i}">在此处打开</button><button class="icon-button" data-remove-app="${i}" aria-label="移除应用">${icon('close')}</button></div></div>`).join('')}</div><div class="note">终端和 iTerm2 可选择新窗口或新标签页。Terminal 新标签页通过 macOS 自动化完成，首次使用时按系统提示授权。</div>`}
function textPage(){return title('FROM WORDS TO POSSIBILITIES','文字工具','灵感、链接、片段，换一种方式带走。')+`<div class="panel text-panel"><label class="muted" for="text-input">输入文字或链接</label><textarea id="text-input" rows="7" placeholder="粘贴一段文字，或你想分享的网址…">${esc(textValue)}</textarea><div class="operation-line"><button class="primary" data-tool="qr">${icon('qr')}生成二维码</button><button class="secondary" data-translate="google">Google 翻译 ↗</button><button class="secondary" data-translate="baidu">百度翻译 ↗</button></div><div class="muted">二维码在本机生成。点击翻译会在浏览器中打开所选服务，并将输入的文字传给该服务。</div></div>${resultView()}`}
function workbench(){return title('YOUR EVERYDAY SHORTCUTS','操作台','选中一些文件，把手边的小事一次做好。')+context()+`<div class="tool-grid">${toolButton('create','file','新建文件')}${toolButton('copy','copy','复制到…')}${toolButton('move','send','移动到…')}${toolButton('cut','cut','剪切')}${toolButton('paste','copy','粘贴')}${toolButton('info','hash','查看校验值')}${toolButton('convert:png','image','图片转 PNG')}${toolButton('compress','archive','压缩为 ZIP')}${toolButton('open_default','arrow','用默认应用打开')}</div>${resultView()}`}
const settings=[['showTray','显示菜单栏图标','RightClick 不在 Dock 显示。单击顶部图标打开，右键可退出；关闭图标后仍可从应用程序目录打开。'],['hideOnCut','剪切时隐藏文件','粘贴或取消剪切时恢复原始隐藏状态。默认保留可见。'],['confirmDelete','永久删除前确认','关闭后，点击永久删除将直接执行，无法从废纸篓恢复。'],['openAfterCreate','新建后自动打开','使用系统默认应用打开新建的文档。'],['sound','操作完成提示音','完成文件创建后播放系统提示音。'],['terminalTab','终端在新标签页打开','适用于 Terminal 与 iTerm2。'],['externalDisks','在外接磁盘启用右键','包括已挂载的 U 盘和移动硬盘。'],['cloudShortcut','云盘目录快捷菜单','在访达使用 Shift + 右键或鼠标中键，调出快捷菜单。'],['showIcons','显示右键菜单图标','在访达菜单中显示系统图标。']];
function settingsPage(){return title('MAKE IT YOURS','通用设置','按照自己的习惯，留下最顺手的方式。')+`<div class="panel"><div class="panel-title"><h3>启动与权限</h3><span class="status-chip ${statusInfo.finderEnabled?'':'pending'}">${statusInfo.finderEnabled?'访达扩展已启用':'等待启用访达扩展'}</span></div><div class="row"><div class="text"><strong>访达右键与工具栏</strong><small>启用后，在访达空白处或文件上右键使用。</small></div><button class="secondary" data-action="enable-finder">系统设置</button></div><div class="row"><div class="text"><strong>完全磁盘访问</strong><small>受系统保护的文件夹需要由你在系统设置中授权。</small></div><button class="secondary" data-action="disk-permission">前往授权</button></div><div class="row"><div class="text"><strong>辅助功能与自动化</strong><small>终端新标签页、云盘快捷菜单可能需要。</small></div><button class="secondary" data-action="ax-permission">系统设置</button></div><div class="row"><div class="text"><strong>登录时启动</strong><small>由 macOS 管理，可在登录项中随时关闭。</small></div>${switchButton('login',statusInfo.login,'登录时启动')}</div></div><div class="panel"><div class="panel-title"><h3>使用偏好</h3></div>${settings.map(([k,t,d])=>`<div class="row"><div class="text"><strong>${t}</strong><small>${d}</small></div>${switchButton(k,config[k],t)}</div>`).join('')}</div><div class="panel"><div class="row"><div class="text"><strong>右键菜单层级与顺序</strong><small>为每个功能选择一级、二级或三级，并调整分组顺序和显示开关。</small></div><button class="secondary" data-page="menu">配置右键菜单</button></div></div><div class="note">RightClick 独立实现常用右键工具，所有功能永久免费，没有试用期限或设备数量限制。你的配置仅保存在本机。</div>`}
let menuSearch='', menuSaveChain=Promise.resolve();
const menuOpenGroups=new Set();
const menuLevelNames={1:'一级',2:'二级',3:'三级'};
function menuGroups(){return model?.menuCatalog?.groups||[]}
function menuGroupLevel(group){const n=config.menuGroupLevels?.[group.id];return group.isSubmenu?([1,2].includes(n)?n:group.defaultGroupLevel):0}
function menuDefaultLevel(group,entry){const n=menuGroupLevel(group);return n?n+1:entry.defaultLevel}
function menuLevel(entry,group){const n=config.menuLevels?.[entry.id];return [1,2,3].includes(n)?n:menuDefaultLevel(group,entry)}
function menuPath(group,entry){
  const level=menuLevel(entry,group);
  if(level===1)return '访达右键 → '+entry.title;
  if(level===2)return menuGroupLevel(group)===1?'访达右键 → '+group.section+' → '+entry.menuTitle:'访达右键 → RightClick → '+entry.title;
  return '访达右键 → RightClick → '+group.section+' → '+entry.menuTitle;
}
function menuGroupsHtml(){
  const query=menuSearch.trim().toLocaleLowerCase();
  const rows=menuGroups().map((group,index)=>{
    const entries=group.actions.filter(entry=>!query||(group.title+' '+entry.title).toLocaleLowerCase().includes(query));
    if(query&&!entries.length)return '';
    const enabled=!config.disabled.includes('menu:'+group.id)||group.id==='workbench';
    return `<details class="menu-section panel" data-menu-section="${esc(group.id)}" ${query||menuOpenGroups.has(group.id)?'open':''}><summary><strong>${esc(group.title)}</strong><span>${entries.length} 个选项${enabled?'':' · 已隐藏'}</span></summary><div class="menu-group-controls"><span class="muted">${group.id==='workbench'?'操作台入口':`显示本组 <button class="switch ${enabled?'on':''}" data-menu-toggle="${esc(group.id)}" role="switch" aria-checked="${enabled}" aria-label="显示${esc(group.title)}"></button>`}</span>${group.isSubmenu?`<label class="menu-position">分组位置 <select data-menu-group-level="${esc(group.id)}" aria-label="${esc(group.title)}分组位置"><option value="default" ${![1,2].includes(config.menuGroupLevels?.[group.id])?'selected':''}>默认（${group.defaultGroupLevel?menuLevelNames[group.defaultGroupLevel]:'平铺二级'}）</option>${[1,2].map(n=>`<option value="${n}" ${config.menuGroupLevels?.[group.id]===n?'selected':''}>${menuLevelNames[n]} · 子项${menuLevelNames[n+1]}</option>`).join('')}</select></label><button class="secondary" data-menu-inherit="${esc(group.id)}" aria-label="${esc(group.title)}的子项跟随分组">子项跟随分组</button>`:''}<div class="row-actions"><button class="icon-button" data-menu-order="${esc(group.id)}" data-direction="-1" aria-label="上移${esc(group.title)}" ${index===0?'disabled':''}>↑</button><button class="icon-button" data-menu-order="${esc(group.id)}" data-direction="1" aria-label="下移${esc(group.title)}" ${index===menuGroups().length-1?'disabled':''}>↓</button></div></div>${entries.map(entry=>{
      const hidden=!enabled||!entry.enabled;
      const override=config.menuLevels?.[entry.id];
      return `<div class="row menu-entry ${hidden?'menu-entry-hidden':''}"><div class="text"><strong>${esc(entry.title)}${hidden?' <span class="muted">（已隐藏）</span>':''}</strong><small>${esc(menuPath(group,entry))}</small>${!entry.enabled?'<small>请在新建文件设置中启用此格式或模板。</small>':''}</div><select data-menu-level="${esc(entry.id)}" aria-label="${esc(entry.title)}的菜单层级"><option value="default" ${![1,2,3].includes(override)?'selected':''}>${group.isSubmenu?'跟随分组':'默认'}（${menuLevelNames[menuDefaultLevel(group,entry)]}）</option>${[1,2,3].map(n=>`<option value="${n}" ${override===n?'selected':''}>${menuLevelNames[n]}${n===1?' · 直接显示':''}</option>`).join('')}</select></div>`;
    }).join('')||'<div class="empty">此组暂无选项，可在常用目录或开发工具中添加。</div>'}</details>`;
  }).join('');
  return rows||'<div class="empty">没有匹配的菜单选项</div>';
}
function menuPage(){
  const counts={1:0,2:0,3:0};
  menuGroups().forEach(g=>{if(!config.disabled.includes('menu:'+g.id)||g.id==='workbench')g.actions.filter(a=>a.enabled).forEach(a=>counts[menuLevel(a,g)]++)});
  return title('RIGHT WHERE YOU NEED IT','右键菜单','分组位置与子项位置独立设置，子项默认跟随分组。',`<button class="secondary" data-action="reset-menu-levels">恢复默认层级</button>`)+`<div class="menu-depths"><div><b>一级 <span>${counts[1]} 个功能</span></b><p>访达右键直接可见</p></div><div><b>二级 <span>${counts[2]} 个功能</span></b><p>一级分组 → 子项，或 RightClick → 功能</p></div><div><b>三级 <span>${counts[3]} 个功能</span></b><p>RightClick → 分组 → 功能</p></div></div><div class="toolbar menu-search"><input id="menu-search" type="search" aria-label="搜索右键菜单选项" placeholder="搜索功能、文件类型或应用…" value="${esc(menuSearch)}"><span class="muted">自动保存，下次右键生效</span></div><div id="menu-groups">${menuGroupsHtml()}</div><div class="note">例如：将“新建文件”分组放到一级，默认子项就会放在其二级菜单；单独将“新建 Markdown”设为一级，即可直接显示。改变分组位置会保留子项的单独设置；点击“子项跟随分组”可清除本组子项的单独设置。新增模板、目录和应用默认跟随所属分组。隐藏开关优先，恢复默认层级不改变顺序或开关。</div>`;
}
function queueMenuChange(edit){
  const work=async()=>{
    const next={...config,menuLevels:{...(config.menuLevels||{})},menuGroupLevels:{...(config.menuGroupLevels||{})},disabled:[...config.disabled],menuOrder:[...config.menuOrder]};
    edit(next);
    try{
      await rpc({cmd:'save_config',config:next});
      config=next;model.config=next;
      await native('apply_settings',{config:next});
      model.menuCatalog=await native('menu_catalog',{config:next});
      if(page==='menu')render();
      toast('菜单已保存，下次右键生效');
    }catch(error){if(page==='menu')render();throw error}
  };
  menuSaveChain=menuSaveChain.catch(()=>{}).then(work);
  return menuSaveChain;
}
function setMenuLevel(id,value){
  if(!menuGroups().some(g=>g.actions.some(a=>a.id===id)))throw new Error('此菜单选项已不存在，请重新打开页面');
  if(value!=='default'&&![1,2,3].includes(Number(value)))throw new Error('请选择一级、二级或三级');
  return queueMenuChange(next=>{if(value==='default')delete next.menuLevels[id];else next.menuLevels[id]=Number(value)});
}
function setMenuGroupLevel(id,value){
  const group=menuGroups().find(g=>g.id===id);if(!group?.isSubmenu)return Promise.resolve();
  if(value!=='default'&&![1,2].includes(Number(value)))throw new Error('分组请选择一级或二级，子项默认跟随分组');
  return queueMenuChange(next=>{if(value==='default')delete next.menuGroupLevels[id];else next.menuGroupLevels[id]=Number(value)});
}
function inheritMenuGroup(id){
  const group=menuGroups().find(g=>g.id===id);if(!group?.isSubmenu)return Promise.resolve();
  return queueMenuChange(next=>group.actions.forEach(entry=>{delete next.menuLevels[entry.id]}));
}
function resetMenuLevels(){return queueMenuChange(next=>{next.menuLevels={};next.menuGroupLevels={}})}
function toggleMenuGroup(id){return queueMenuChange(next=>{const key='menu:'+id;next.disabled=next.disabled.includes(key)?next.disabled.filter(x=>x!==key):[...next.disabled,key]})}
function moveMenuGroup(id,direction){return queueMenuChange(next=>{const order=menuGroups().map(g=>g.id),from=order.indexOf(id),to=from+direction;if(from>=0&&to>=0&&to<order.length){[order[from],order[to]]=[order[to],order[from]];next.menuOrder=order}})}
document.addEventListener('change',async e=>{if(e.target.dataset.menuLevel)await setMenuLevel(e.target.dataset.menuLevel,e.target.value);else if(e.target.dataset.menuGroupLevel&&e.target.value)await setMenuGroupLevel(e.target.dataset.menuGroupLevel,e.target.value)});
document.addEventListener('toggle',e=>{const id=e.target.dataset?.menuSection;if(id){if(e.target.open)menuOpenGroups.add(id);else menuOpenGroups.delete(id)}},true);

function resultView(){if(!lastResult)return '';let paths=lastResult.paths||[];return `<div class="result"><div class="title-line"><h3>${esc(lastLabel||'操作结果')}</h3><button class="icon-button" data-action="clear-result" aria-label="关闭结果">×</button></div>${paths.map(p=>`<div class="result-row"><span>已生成</span><code>${esc(p)}</code></div>`).join('')}${Array.isArray(lastResult.files)?lastResult.files.map(f=>`<h3 style="margin-top:18px">${esc(f.name)}</h3>${['bytes','permissions','md5','sha1','sha256','sha512'].filter(k=>f[k]!==undefined).map(k=>`<div class="result-row"><span>${k.toUpperCase()}</span><code>${esc(f[k])}</code></div>`).join('')}`).join(''):''}${lastResult.largest?`<p class="muted">总计 ${formatBytes(lastResult.bytes)} · ${lastResult.files} 个文件 · ${lastResult.unreadable} 个目录无法读取</p>${lastResult.largest.map(f=>`<div class="result-row"><span>${formatBytes(f.bytes)}</span><code>${esc(f.path)}</code></div>`).join('')}`:''}${lastResult.message?`<p class="muted">${esc(lastResult.message)}</p>`:''}${lastResult.errors?.length?`<pre>${esc(JSON.stringify(lastResult.errors,null,2))}</pre>`:''}${paths.length?`<div class="operation-line"><button class="secondary" data-action="reveal-result">在访达中显示</button><button class="secondary" data-action="open-result">打开结果</button>${lastLabel==='二维码'?'<button class="secondary" data-action="copy-qr">复制二维码图片</button>':''}</div>`:''}</div>`}
function formatBytes(b){return b>1073741824?(b/1073741824).toFixed(2)+' GB':b>1048576?(b/1048576).toFixed(1)+' MB':b>1024?(b/1024).toFixed(1)+' KB':b+' B'}
function render(){if(!model)return;$('#nav').innerHTML=nav.map(([id,i,n],idx)=>(idx===8?'<div class="nav-divider"></div>':'')+`<button class="nav-item ${page===id?'active':''}" data-page="${id}">${icon(i)}<span>${n}</span></button>`).join('');$('#breadcrumb').textContent='工作空间 / '+nav.find(x=>x[0]===page)?.[2];$('#main').innerHTML=({overview,templates:templatesPage,send:()=>foldersPage('send'),favorites:()=>foldersPage('favorites'),icons:iconPage,tools:toolsPage,apps:appsPage,text:textPage,workbench,menu:menuPage,settings:settingsPage})[page]();$('#choose-context').textContent=cwd}
function go(id){page=id;render();$('#main').scrollTop=0}
async function dialog(title,html,submit='确定',danger=false){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog-submit').textContent=submit;$('#dialog-submit').className=danger?'danger':'primary';const d=$('#dialog');d.showModal();return new Promise(resolve=>{let finished=false;function close(value){if(finished)return;finished=true;d.close();resolve(value)}$('#dialog-form').onsubmit=e=>{e.preventDefault();close(Object.fromEntries(new FormData(e.target)))};$('#dialog-cancel').onclick=()=>close(null);$('#dialog-close').onclick=()=>close(null);d.oncancel=e=>{e.preventDefault();close(null)}})}
async function choose(kind='file',multiple=false){const r=await native('choose',{kind,multiple});return r.paths||[]}
async function requireFiles(){if(!selection.length){selection=await choose('file',true);render()}return selection.length>0}
async function perform(req,label){if(busy){toast('上一项操作仍在进行');return}busy=true;$('#status').textContent='正在'+label+'…';try{const r=await rpc(req);lastResult=r;lastLabel=label;toast(r.errors?.length?'部分项目未完成，请查看结果':(r.message||label+'完成'),!!r.errors?.length);await reload();render();return r}catch(e){toast(e.message,true);throw e}finally{busy=false;$('#status').textContent='就绪'}}
async function runNative(cmd,params={},label='操作'){return perform({cmd:'native',request:{cmd,...params}},label)}
async function createFile(format='txt',template=null){const res=await dialog('新建文件',`<label>文件名</label><input name="name" value="未命名.${esc(template?.ext||(format==='custom'?'txt':format))}" required autofocus><label>保存目录</label><div class="muted">${esc(cwd)}</div>`,'创建');if(!res)return;const r=await perform({cmd:'create',dir:cwd,name:res.name,...(template?{template:template.id}:{format})},'新建文件');if(r&&config.openAfterCreate)await native('open',{paths:r.paths});if(r&&config.sound)await native('beep')}
async function pickDestination(){const res=await dialog('选择目标目录',`<label>常用目录</label><select name="dir">${config.favorites.map(f=>`<option value="${esc(f.path)}">${esc(f.name)} · ${esc(f.path)}</option>`).join('')}<option value="__choose">选择其他目录…</option></select>`,'继续');if(!res)return null;return res.dir==='__choose'?(await choose('directory'))[0]:res.dir}
async function runTool(id){if(id==='create_custom'){await createFile('custom');return}if(id==='create'){go('templates');return}if(id==='cancel_cut'){await perform({cmd:id},'取消剪切');return}if(id==='paste'){await perform({cmd:id,dir:cwd},'粘贴');return}if(id==='qr'){textValue=$('#text-input')?.value||textValue;if(!textValue.trim()){toast('请输入二维码内容',true);return}await perform({cmd:'qr',text:textValue,dir:cwd},'二维码');return}if(['scan','screenshot','finder_show','finder_hide'].includes(id)){if(id==='scan')await perform({cmd:id,dir:cwd},'扫描目录');else await runNative(id==='screenshot'?id:'finder_hidden',{dir:cwd,show:id==='finder_show'},id==='screenshot'?'截图':'访达显示设置');return}if(!await requireFiles())return;
if(['copy','move'].includes(id)){const dir=await pickDestination();if(dir)await perform({cmd:id,paths:selection,dir},id==='copy'?'复制':'移动');return}
if(id.startsWith('convert:')){await perform({cmd:'convert',paths:selection,dir:cwd,format:id.split(':')[1]},'图片转换');return}
if(id==='rename'){if(selection.length!==1){toast('请只选择一个文件',true);return}const r=await dialog('重命名文件',`<input name="name" value="${esc(selection[0].split('/').pop())}" required>`,'重命名');if(r){const out=await perform({cmd:'rename',paths:selection,name:r.name},'重命名');selection=out.paths;render()}return}
if(id==='repair_name'){const r=await dialog('修复乱码文件名','<p class="muted">先预览名称转换，再选择是否应用。不会修改文件内容。</p><label>原始字节编码</label><select name="encoding"><option value="gbk">GBK → UTF-8</option><option value="big5">Big5 → UTF-8</option><option value="latin1">Latin-1 → UTF-8</option></select>','预览');if(!r)return;const preview=await rpc({cmd:'repair_preview',paths:selection,encoding:r.encoding});const ok=await dialog('确认文件名修复',preview.names.map(x=>`<p class="muted">${esc(x.old)} → ${esc(x.new)}</p>`).join(''),'应用');if(ok)await perform({cmd:'repair_apply',paths:selection,encoding:r.encoding},'文件名修复');return}
if(id==='delete'){if(config.confirmDelete){const ok=await dialog('永久删除这些文件？',`<p class="muted">此操作跳过废纸篓，无法撤销。</p><p class="muted">${selection.map(esc).join('<br>')}</p>`,'永久删除',true);if(!ok)return}await perform({cmd:'delete',paths:selection,confirmed:true},'永久删除');selection=[];render();return}
if(id==='dissolve'){if(!await dialog('解散所选文件夹？','<p class="muted">将其内容移到上一级目录，然后移除空文件夹。同名项目会另存。</p>','解散'))return}
if(['preview','pin','airdrop','wallpaper','trash'].includes(id)){await runNative(id,{paths:selection},toolsList.find(x=>x[0]===id)?.[2]||id);return}
if(id==='open_default'){await runNative('open',{paths:selection},'打开文件');return}
if(id==='reset_icon'){await runNative('icon',{paths:selection,reset:true},'恢复图标');return}
if(id.startsWith('extension_')){await runNative('extension_hidden',{paths:selection,hidden:id==='extension_hide'},'扩展名设置');return}
if(id==='compress7z'||id==='encrypt'){let password='';let format='7z';if(id==='encrypt'){const r=await dialog('加密压缩','<label>归档格式</label><select name="format"><option value="7z">7z (AES-256)</option><option value="zip">ZIP (AES-256)</option></select><label>密码</label><input name="password" type="password" required autocomplete="new-password"><p class="muted">密码仅用于本次压缩，不会保存到设置。</p>','压缩');if(!r)return;password=r.password;format=r.format}await perform({cmd:'archive7z',paths:selection,dir:cwd,format,password},'压缩');return}
if(id==='extract'){let password='';const res=await dialog('解压归档','<p class="muted">每个归档会解压到新的独立文件夹。</p><label>密码（未加密可留空）</label><input name="password" type="password" autocomplete="off">','解压');if(!res)return;password=res.password;await perform({cmd:'extract_auto',paths:selection,dir:cwd,password},'解压');return}
await perform({cmd:id==='unhidden'?'hidden':id,paths:selection,dir:id==='shortcut'?model.home+'/Desktop':cwd,hidden:id==='hidden',format:'zip'},toolsList.find(x=>x[0]===id)?.[2]||'压缩')}
async function action(id){switch(id){case 'reset-menu-levels':await resetMenuLevels();break;case 'choose-dir':{const p=(await choose('directory'))[0];if(p){cwd=p;render()}break}case 'choose-files':selection=await choose('file',true);render();break;case 'clear-files':selection=[];render();break;case 'enable-finder':await native('settings',{pane:'extensions'});break;case 'disk-permission':await native('settings',{pane:'disk'});break;case 'ax-permission':await native('settings',{pane:'accessibility'});break;case 'clear-result':lastResult=null;render();break;case 'reveal-result':await native('reveal',{paths:lastResult.paths});break;case 'open-result':await native('open',{paths:lastResult.paths});break;case 'copy-qr':await native('clipboard_image',{paths:lastResult.paths});toast('二维码已复制');break;case 'add-favorite':{const p=(await choose('directory'))[0];if(p){if(config.favorites.some(x=>x.path===p)){toast('此目录已在列表中');break}config.favorites.push({name:p.split('/').pop(),path:p});await save()}break}case 'add-app':{const p=(await choose('app'))[0];if(p){const a=await native('app_info',{paths:[p]});config.apps.push(a);await save();installedApps=(await native('apps',{apps:config.apps})).apps;render()}break}case 'add-template':{const p=(await choose('file'))[0];if(!p)break;const r=await dialog('导入文件模板',`<label>模板名称</label><input name="name" value="${esc(p.split('/').pop())}" required><p class="muted">模板会复制到 RightClick 的本地资料目录。</p>`,'导入');if(r){await rpc({cmd:'template_add',path:p,name:r.name});await reload();await native('apply_settings',{config});render();toast('模板已导入')}break}case 'custom-icon':{if(!await requireFiles())break;const p=(await choose('image'))[0];if(p)await runNative('icon',{paths:selection,image:p},'自定义图标');break}}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.menuInherit){await inheritMenuGroup(d.menuInherit);return}if(d.menuToggle){await toggleMenuGroup(d.menuToggle);return}if(d.menuOrder){await moveMenuGroup(d.menuOrder,Number(d.direction));return}if(d.page){go(d.page);return}if(d.action){await action(d.action);return}if(d.tool){await runTool(d.tool);return}if(d.create){await createFile(model.formats.find(f=>f.id===d.create)?.ext||'txt',d.custom==='true'?config.templates.find(t=>t.id===d.create):null);return}if(d.setting){const key=d.setting;if(key==='login'){await native('login',{enabled:!statusInfo.login});statusInfo=await native('status');render();return}if(key.startsWith('format:')||key.startsWith('menu:')){config.disabled=config.disabled.includes(key)?config.disabled.filter(x=>x!==key):[...config.disabled,key]}else{if(key==='confirmDelete'&&config[key]){if(!await dialog('关闭永久删除确认？','<p class="muted">关闭后，点击永久删除会立即删除文件且不可恢复。</p>','关闭确认',true))return}config[key]=!config[key]}await save();return}if(d.removeTemplate){config.templates=config.templates.filter(t=>t.id!==d.removeTemplate);await save();return}if(d.removeFavorite!==undefined){config.favorites.splice(+d.removeFavorite,1);await save();return}if(d.editFavorite!==undefined){const f=config.favorites[+d.editFavorite];const r=await dialog('修改显示名称',`<input name="name" value="${esc(f.name)}" required>`,'保存');if(r){f.name=r.name;await save()}return}if(d.openFavorite!==undefined){await native('open',{paths:[config.favorites[+d.openFavorite].path]});return}if(d.transfer){if(await requireFiles())await perform({cmd:d.transfer,paths:selection,dir:config.favorites[+d.index].path},d.transfer==='copy'?'复制':'移动');return}if(d.openApp!==undefined){await runNative('open_app',{paths:selection.length?selection:[cwd],app:config.apps[+d.openApp].id,tab:config.terminalTab},'打开应用');return}if(d.removeApp!==undefined){config.apps.splice(+d.removeApp,1);await save();return}if(d.color){if(await requireFiles())await runNative('icon',{paths:selection,color:d.color},'文件夹图标');return}if(d.translate){textValue=$('#text-input')?.value||textValue;if(textValue.trim())await native('translate',{text:textValue,provider:d.translate});else toast('请输入要翻译的文字',true);return}if(d.order!==undefined){let i=+d.order;if(i){[config.menuOrder[i-1],config.menuOrder[i]]=[config.menuOrder[i],config.menuOrder[i-1]];await save()}}});
document.addEventListener('input',e=>{if(e.target.id==='text-input')textValue=e.target.value;if(e.target.id==='menu-search'){menuSearch=e.target.value;$('#menu-groups').innerHTML=menuGroupsHtml()}});$('#choose-context').onclick=()=>action('choose-dir');
window.refreshNativeStatus=async()=>{statusInfo=await native('status');if(['settings','overview'].includes(page)&&!$('#dialog').open)render()};
window.receiveFinder=async req=>{if(req.dir)cwd=req.dir;if(req.paths)selection=req.paths;lastResult=null;go('workbench');if(req.cmd==='workbench')return;if(req.cmd==='text'){textValue=req.text||'';go('text');return}if(req.cmd==='create'&&req.format){await createFile(req.format);return}if(req.cmd==='create'&&req.template){await createFile('txt',config.templates.find(t=>t.id===req.template));return}if(req.cmd==='favorite'){await native('open',{paths:[req.destination]});return}if((req.cmd==='copy'||req.cmd==='move')&&req.destination){await perform({cmd:req.cmd,paths:selection,dir:req.destination},req.cmd==='copy'?'复制':'移动');return}if(req.cmd==='open_app'){await runNative('open_app',{paths:selection.length?selection:[cwd],app:req.app,tab:config.terminalTab},'打开应用');return}if(req.cmd==='icons'){go('icons');return}if(req.cmd==='convert'){if(req.format)await runTool('convert:'+req.format);else go('tools');return}await runTool(req.cmd)};
(async()=>{try{await reload();statusInfo=await native('status');installedApps=(await native('apps',{apps:config.apps})).apps||[];render();await rpc({cmd:'ready'});}catch(e){$('#main').innerHTML=`<div class="empty">${esc(e.message)}</div>`;toast(e.message,true)}})();
